name: MLOps_Pipeline_Infartos

on:
  push:
    branches: [ main ] # Se activa cada vez que subes algo a la rama main

jobs:
  build-and-train:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Instalar dependencias
      run: pip install -r requirements.txt

    - name: Ejecutar Preprocesamiento
      run: python src/preprocessing.py

    - name: Inspeccionar Datos Procesados
      run: |
            echo "--- LISTA COMPLETA DE COLUMNAS ---"
            head -n 1 data/processed/data_clean.csv
            echo -e "\n--- PRIMERAS 3 FILAS DE DATOS ---"
            head -n 4 data/processed/data_clean.csv

    - name: Ejecutar Entrenamiento
      run: python src/train.py

    - name: Ejecutar Prediccion
      run: python src/predict.py

    - name: Guardar Modelo como Artefacto
      uses: actions/upload-artifact@v4
      with:
        name: modelo-entrenado
        path: models/

